[package]
name = "cerberus"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"  # http server
reqwest = { version = "0.11.13", features = ["json"] }  # http client
tokio = { version = "1.22.0", features = ["full"] }  # async framework
futures = "0.3.25"  # async framework

serde = { version = "1.0.148", features = ["derive"] }
criterion = "0.4.0"  # benchmarking

frost-ed25519 = { git = "https://github.com/ZcashFoundation/frost" }  # threshold signatures
