[package]
name = "distrib-mods"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"  # for communication between moderators
serde = { version = "1.0.148", features = ["derive"] }
bincode = "1.3.3"
# frost-ed25519 = { git = "https://github.com/ZcashFoundation/frost" }
reqwest = { version = "0.11.13", features = ["json"] }
# criterion = "0.4.0"
tokio = { version = "1.22.0", features = ["macros"] }
futures = "0.3.25"
