[package]
name = "cerberus"
version = "0.1.0"
edition = "2021"

[dependencies]
# async 
tokio = { version = "1.22.0", features = ["full"] }
futures = "0.3.25"

# serialization
serde = { version = "1.0.148", features = ["derive"] }
serde_arrays = "0.1.0"
bincode = "1.3.3"

# parameters
konst = "0.3.4"
load-dotenv = "0.1.2"

# http
reqwest = { version = "0.11.13", features = ["json"] }
tiny_http = "0.12.0"

# crypto
curve25519-dalek = { version = "4.0.0-pre.1", features = [
    "serde",
], package = "curve25519-dalek-ml" }
vsss-rs = { version = "2.1.0", features = ["std"] }
sha2 = "0.10.6"
rand = "0.8.5"
# frost-ristretto255 = { git = "https://github.com/alipatti/frost", branch = "add-serde" }
# frost-core = { git = "https://github.com/alipatti/frost", branch = "add-serde" }
frost-ristretto255 = { path = "../frost/frost-ristretto255" }
frost-core = { path = "../frost/frost-core" }


# misc
array-init = "2.1.0"
