services:
  # tester:
  #   build:
  #     context: .
  #     target: tester

  bencher:
    build:
      context: .
      target: bencher

    deploy:
      resources:
        reservations:
          cpus: "1"
          memory: "1g"
        limits:
          cpus: "1"
          memory: "1g"

    volumes:
      - "./benches/results:/usr/src/cerberus/target/criterion"

  moderator:
    deploy:
      mode: replicated
      replicas: 7
      resources:
        reservations:
          cpus: "1"
          memory: "1g"
        limits:
          cpus: "1"
          memory: "1g"

    build:
      context: .
      target: moderator
