services:
  # coordinator:
  #   env_file: .env
  #   build:
  #     context: .
  #     target: coordinator
  #   deploy:
  #     resources:
  #       reservations:
  #         cpus: "1"
  #         memory: "1g"

  bencher:
    env_file: .env

    build:
      context: .
      target: bencher

    deploy:
      resources:
        reservations:
          cpus: "1"
          memory: "1g"
        limits:
          cpus: "1"
          memory: "1g"

  moderator:
    deploy:
      mode: replicated
      replicas: ${CERBERUS_N_MODERATORS}
      resources:
        reservations:
          cpus: "1"
          memory: "1g"
        limits:
          cpus: "1"
          memory: "1g"

    build:
      context: .
      target: moderator
