services:
  coordinator:
    env_file: .env
    build:
      context: .
      target: coordinator

  moderator:
    # this is depricated, but it still works despite the
    # linter error. see: https://linuxhint.com/docker_compose_scale/
    # TODO: migrate to new version of compose spec
    scale: ${CERBERUS_N_MODERATORS}
    build:
      context: .
      target: moderator
