services:
  coordinator:
    env_file: .env
    build:
      context: .
      target: coordinator

  moderator:
    scale: ${CERBERUS_N} # see: https://linuxhint.com/docker_compose_scale/
    build:
      context: .
      target: moderator
